name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Install Qt
      run: |
        curl https://download.qt.io/archive/qt/4.8/4.8.7/qt-everywhere-opensource-src-4.8.7.zip -o /tmp/qt4.zip
        unzip /tmp/qt4.zip
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1
      with:
        submodule_update: ON
        # run_tests: ON
        # unit_test_build: -Dtest=ON
